### ISSUE TITLE
Change image stocks for symposia

### ISSUE THREAD

**Issue by davieiycode** [bppugm/biomic-2019#5]

**Comment by nisakusumaa** [comment]
1. Bioinformatics and Biological Data Mining
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/jsoe/45633508952/in/photolist-2arwTP5-2arwTdL-2d8B1JA-2d8B1FQ-2arwTKN-2cwtywb-2arwTYy-2d9wv9i-NQG3cX-HZbmhm-2bdefK4-29QigNJ-92Fia5-2aRPPmj-N8XBno-2bdefqr-NQG2LB-29QigAQ-2buTTd1-RuxN4j-MTEX1r-NQG3h6-2cwtEn7-Qt67zW-2aRPPxm-NQG2vM-29QigEs-2ceJJiZ-2aRPQdj-2ceJJLx-29QigUf-2aRPPHm-NQG3qT-2aRPPUU-2ceJJwp-2cwtyph-2ceJKf8-2ceJKrF-2cwtyjN-2cwty8A-2bdefcR-2cwtExh-KzSAFQ-LM1ciM-NQG2HR-Qt67CS-2buTTo1-2cAWnnr-NQG3oi-28TtnT9" title="UCSD-JacobsSchool-20181011-Zhang_Lab-cell_mapping-04030-8MP"><img src="https://farm5.staticflickr.com/4852/45633508952_ee19f59a4e_z.jpg" width="640" height="427" alt="UCSD-JacobsSchool-20181011-Zhang_Lab-cell_mapping-04030-8MP"></a>
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/jsoe/45633509242/in/album-72157673009353107/" title="UCSD-JacobsSchool-20181011-Zhang_Lab-cell_mapping-04021-8MP"><img src="https://farm2.staticflickr.com/1951/45633509242_712d5aaaa9_z.jpg" width="640" height="427" alt="UCSD-JacobsSchool-20181011-Zhang_Lab-cell_mapping-04021-8MP"></a>


2. Biomedical Sciences
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/davidjthomas/3716560187/in/photolist-aEhXf3-dA1Wz8-4ptFBx-5HELjq-4FpGsT-5HLTap-2dhfMnU-3nqgTF-5HEMFS-5HC3sf-5HxMfp-5HKmce-5HELVb-6KjH6V-5HKkdz-5HC3Ks-cAV2ry-6KoRbq-6KjGFp-5HxHFR-6KoRBu-TYkhjg-5HLcZn-3nuKsu-5HENkN-5HKiJn-6KjHsD-5HAre8-5HPCew-5HKks2-5HKkG6-5HEPhm-5HAu8K-6KoQRA-5HCzXN-5HAvQk-6EqkRV-3nuKLb-3nuKFd-buDdHn-4UbXY1-3nqhs8-5HR76u-6KjHmv-3nuK8W-zswo5Q-6KjHuv-6KoQUf-a144is-Hk3dKB" title="P7131168"><img src="https://farm4.staticflickr.com/3525/3716560187_7ab6403e44_z.jpg" width="640" height="480" alt="P7131168"></a>
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/maxorz/46029305242/in/photolist-2d8sdP5-c1b9m9-c1b8E1-5i64wZ-pi4v6-kkoo7v-qZW5TU-qkGZXa-6tLMyJ-PdtnVY-efLjzT-28ndAbW-9fApck-rxt6VH-6YMEGu-5fDZGL-2bhwAft-dXwEJG-bCkz1A-i9dpBM-c1aGmj-c1b8eN-hE6Hu-c1aMLE-gTyCPh-fkSsM5-bR6Zik-bCkyYL-9xhqso-6LYZRQ-bQRqcT-c1b8Vy-c1bfjh-rhtsgn-6XXnW7-c1aGK7-c1b9FL-pT1Gqo-pT1z63-c1aR2u-8S8u3R-c1aQLw-4m671x-98mTsf-c1aDc5-c1bkYQ-c1beys-c1bcZo-WVQvcy-rhqfvG" title="Fluorescent petri dish"><img src="https://farm5.staticflickr.com/4853/46029305242_4c91958431_z.jpg" width="640" height="427" alt="Fluorescent petri dish"></a>
<a href="https://www.freepik.com/free-photos-vectors/background">Background photo created by kjpargeter - www.freepik.com</a>

3. Biomedical Engineering
![image](https://user-images.githubusercontent.com/47167841/53547204-f7b14580-3b60-11e9-8eba-5649f1bee8ef.png)
![image](https://user-images.githubusercontent.com/47167841/53547820-99856200-3b62-11e9-8198-1dfdf2dfaa63.png)


4. Biomolecular and Biotechnology
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/skynoir/8269371411/in/faves-52752122@N04/" title="Laboratory Science - biomedical"><img src="https://farm9.staticflickr.com/8363/8269371411_678131abf4_z.jpg" width="640" height="425" alt="Laboratory Science - biomedical"></a>
![image](https://user-images.githubusercontent.com/47167841/53546484-0c8cd980-3b5f-11e9-8ab5-52e7f9339170.png)
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/z33be/5214588082/in/faves-52752122@N04/" title="Alter Nature: We Can - BCL (Georg Tremmel &amp; Shiho Fukuhara) - Common Flowers - Flower Commons (2009)"><img src="https://farm5.staticflickr.com/4084/5214588082_7515eab165_z.jpg" width="640" height="427" alt="Alter Nature: We Can - BCL (Georg Tremmel &amp; Shiho Fukuhara) - Common Flowers - Flower Commons (2009)"></a>

5. Drug Development and Nutraceutical
![image](https://user-images.githubusercontent.com/47167841/53312671-8ff0c580-38e8-11e9-897e-6019e787ed2b.png)

6. Public Health
![image](https://user-images.githubusercontent.com/47167841/53545849-61c7eb80-3b5d-11e9-8c20-2a364dafc201.png)
![image](https://user-images.githubusercontent.com/47167841/53545925-9fc50f80-3b5d-11e9-9028-f487941a5742.png)
<a data-flickr-embed="true"  href="https://www.flickr.com/photos/ravikomatireddy/7336654514/in/faves-52752122@N04/" title="jsc2012e053687"><img src="https://farm8.staticflickr.com/7244/7336654514_4e18325868_z.jpg" width="640" height="426" alt="jsc2012e053687"></a>
